feat: ✨ finalize expert form contact with email attachment
dnum-mi/basegun pull request #541
Opened 2024-08-05 13:11 UTC by nutfdt

2024-08-06 15:38 UTC, thomashbrnrd requested changes

2024-08-06 15:38 UTC, thomashbrnrd commented on frontend/src/utils/authentication.ts
> +  automaticSilentRenew: false,
Je pense pas qu'il faille mettre ça à false, sinon à justifier ?

2024-08-06 15:38 UTC, thomashbrnrd commented on backend/src/utils.py
> +            # audience=["master-realm", "account"],
Pourquoi ?

2024-08-07 12:07 UTC, nutfdt commented on backend/src/utils.py
> +            # audience=["master-realm", "account"],
Dans le payload d'un token JWT on a pas de champ `aud`  ou `audience` donc si on laisse ça dans le code, on pourra pas décoder le token. Donc soit on l'enlève soit on mets à jour le fichier de configuration de Keycloak

2024-08-07 12:11 UTC, nutfdt commented on frontend/src/utils/authentication.ts
> +  automaticSilentRenew: false,
J'ai repassé la valeur en true, il suffit juste d'augmenter la longueur de vie d'un token

2024-08-08 07:45 UTC, thomashbrnrd requested changes

2024-08-08 07:45 UTC, thomashbrnrd commented on frontend/src/utils/authentication.ts
> +  automaticSilentRenew: true,
Tu peux supprimer ça, c'est à true par défaut

2024-08-08 07:45 UTC, thomashbrnrd commented on frontend/src/views/GuideAskingExpertise/ExpertiseForm.vue
> +  <div>
Tu devrais utiliser la grille non ?
https://www.systeme-de-design.gouv.fr/fondamentaux/grille-et-points-de-rupture/

2024-08-08 08:09 UTC, nutfdt commented on frontend/src/utils/authentication.ts
> +  automaticSilentRenew: true,
C'est good

2024-08-08 08:09 UTC, nutfdt commented on frontend/src/views/GuideAskingExpertise/ExpertiseForm.vue
> +  <div>
Yess merci c'est fait

2024-08-09 07:35 UTC, thomashbrnrd approved these changes

2024-08-09 08:07 UTC, merged