refactor: :recycle: use env variable for contact numbers
dnum-mi/basegun pull request #547
Opened 2024-08-09 14:38 UTC by nutfdt

2024-08-30 08:18 UTC, thomashbrnrd requested changes

2024-08-30 08:18 UTC, thomashbrnrd commented on backend/tests/test_api.py
> +    def test_405(self):
405 ? ça devrait plutôt être 401 non ?

2024-08-30 08:18 UTC, thomashbrnrd commented on backend/src/router.py
> +    return PHONE_NUMBER, CELLPHONE_NUMBER
Ce serait mieux de faire un tableau avec des clés, du genre : 
```json
{
   "phone": "xxx",
   "cellphone": "xxx",
}

2024-08-30 08:18 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +            <span v-if="authIDP === 'proxyma'"
`user.auth_idp` ce serait plus clair quand même

2024-10-07 09:00 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +          <div v-if="userAuthIDP === 'cheops'">
Si l'utilisateur n'est ni cheops, ni proxyma, que se passe t'il ?

2024-10-07 09:00 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> -const user = ref(Object || null);
Pourquoi ne pas garder l'objet user ?

2024-10-07 09:00 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +  try {
Est ce qu'il ne vaudrait pas mieux gérer les erreurs comme ceci : https://axios-http.com/docs/handling_errors ?

2024-10-07 09:30 UTC, nutfdt commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +          <div v-if="userAuthIDP === 'cheops'">
Pas faux, j'ai changé ça

2024-10-07 09:32 UTC, nutfdt commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> -const user = ref(Object || null);
On en a plus besoin vu qu'on récupère les informations de l'utilisateur via une requête 

```
// Récupération des données de l'utilisateur
const getUserData = async () => {
  try {
    const user = await mgr.getUser();
    getAccessToken.value = user?.access_token;
    userAuthIDP.value = user?.profile.auth_idp;
  } catch (error) {
    console.error(
      "Erreur pendant la récupération des données de l'utilisateur :",
      error,
    );
  }
};
```

2024-10-08 07:50 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +  access_token.value = user?.access_token;
est ce qu'on ne peut pas simplement utiliser `user.access_token` au lieu de créer une nouvelle variable dédiée ?
même chose pour `idp`.

2024-10-08 11:18 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +  const result = await mgr.getUser();
Pourquoi ne pas faire `user.value = await mgr.getUser();`

2024-10-08 11:19 UTC, thomashbrnrd commented on frontend/src/views/GuideContactExpert/ExpertSituation.vue
> +    await getIRCGNDetails();
Je pense qu'on pourrait faire le call dans tous les cas, et renvoyer une 403 côté backend si l'idp n'est pas proxyma

2024-10-09 07:46 UTC, thomashbrnrd approved these changes

2024-10-09 07:50 UTC, merged